data:
  train_data_path: "data/train.csv"
  test_data_path: "data/test.csv"
  features: ["amount", "transaction_type", "account_balance", "time"]

model:
  type: "xgboost"
  parameters:
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 100

training:
  batch_size: 32
  epochs: 10
  validation_split: 0.2
